const PRODUCTS=[
{slug:"set-polo-kem-wide-pants",name:"Set Polo Kem Wide Pants",cat:["nam","new"],price:429000,img:"assets/products/guno-polo-cream-widepants.jpg",colors:["#f5f0e8","#2d3436","#34495e"],sizes:["S","M","L","XL"],desc:"Set polo kem phối quần ống rộng, phù hợp mặc hàng ngày.",badge:"New",rating:4.8,reviews:128},
{slug:"set-polo-navy-wide-pants",name:"Set Polo Navy Wide Pants",cat:["nam","new"],price:449000,oldPrice:529000,img:"assets/products/guno-polo-navy-widepants.jpg",colors:["#2c3e50","#ecf0f1","#bdc3c7"],sizes:["M","L","XL","2XL"],desc:"Set polo navy phối quần ống rộng.",badge:"Bán chạy",rating:4.7,reviews:95},
{slug:"set-polo-grey-wide-pants",name:"Set Polo Grey Wide Pants",cat:["nam"],price:419000,img:"assets/products/guno-polo-grey-widepants.jpg",colors:["#b2bec3","#2d3436","#dfe6e9"],sizes:["S","M","L","XL"],desc:"Set polo xám tro phối quần wide pants.",rating:4.6,reviews:72},
{slug:"set-polo-den-wide-pants",name:"Set Polo Đen Wide Pants",cat:["nam"],price:399000,oldPrice:499000,img:"assets/products/guno-polo-black-widepants.jpg",colors:["#2d3436","#636e72","#dfe6e9"],sizes:["M","L","XL","2XL"],desc:"Set polo đen phối quần ống rộng.",discount:20,rating:4.5,reviews:83},
{slug:"set-polo-hong-wide-pants",name:"Set Polo Hồng Wide Pants",cat:["nu","new"],price:429000,img:"assets/products/guno-polo-pink-widepants.jpg",colors:["#fab1a0","#2d3436","#dfe6e9"],sizes:["XS","S","M","L"],desc:"Set polo hồng pastel dành cho nữ.",badge:"New",rating:4.9,reviews:64},
{slug:"ao-thun-guno-trang",name:"Áo thun GUNO trắng",cat:["nam","nu"],price:199000,img:"assets/products/guno-tshirt-white.jpg",colors:["#fff","#2d3436","#636e72"],sizes:["S","M","L","XL"],desc:"Áo thun cổ tròn cotton compact.",badge:"Essential",rating:4.4,reviews:210},
{slug:"ao-thun-guno-den",name:"Áo thun GUNO đen",cat:["nam","nu"],price:199000,img:"assets/products/guno-tshirt-black.jpg",colors:["#2d3436","#fff","#636e72"],sizes:["S","M","L","XL"],desc:"Áo thun đen cotton compact.",badge:"Daily",rating:4.5,reviews:185},
{slug:"set-active-den-do",name:"Set Active Đen Đỏ",cat:["the-thao","nam"],price:359000,oldPrice:449000,img:"assets/products/guno-active-black-red.jpg",colors:["#2d3436","#d63031","#dfe6e9"],sizes:["S","M","L","XL"],desc:"Bộ đồ thể thao active.",discount:25,rating:4.7,reviews:56},
{slug:"set-active-kem-do",name:"Set Active Kem Viền Đỏ",cat:["the-thao","nu","sale"],price:339000,oldPrice:429000,img:"assets/products/guno-active-cream-red.jpg",colors:["#f5f0e8","#d63031","#2d3436"],sizes:["XS","S","M","L"],desc:"Set active kem viền đỏ thể thao nữ.",discount:20,rating:4.6,reviews:41},
{slug:"set-active-den-kem",name:"Set Active Đen Kem",cat:["the-thao","nam"],price:349000,img:"assets/products/guno-active-black-cream.jpg",colors:["#2d3436","#f5f0e8"],sizes:["M","L","XL"],desc:"Bộ active đen phối kem.",rating:4.5,reviews:38},
{slug:"ao-polo-den-short",name:"Áo Polo Đen Short",cat:["nam"],price:279000,img:"assets/products/guno-polo-black-short.jpg",colors:["#2d3436","#2c3e50","#636e72"],sizes:["S","M","L","XL"],desc:"Áo polo đen kết hợp quần short.",rating:4.3,reviews:92},
{slug:"ao-polo-navy-short",name:"Áo Polo Navy Short",cat:["nam"],price:289000,img:"assets/products/guno-polo-navy-short.jpg",colors:["#2c3e50","#2d3436","#b2bec3"],sizes:["S","M","L","XL"],desc:"Áo polo navy pique trẻ trung.",rating:4.4,reviews:78},
{slug:"sweatset-pink-short",name:"Sweatset Hồng Short",cat:["nu","sale"],price:319000,oldPrice:399000,img:"assets/products/guno-sweatset-pink-short.jpg",colors:["#fab1a0","#2d3436","#dfe6e9"],sizes:["XS","S","M","L"],desc:"Set sweat hồng quần short nữ.",discount:20,rating:4.8,reviews:33},
{slug:"ao-tee-kem-short",name:"Áo Tee Kem Short",cat:["nam","nu"],price:189000,img:"assets/products/guno-tee-cream-short.jpg",colors:["#f5f0e8","#2d3436"],sizes:["S","M","L","XL"],desc:"Áo tee kem basic.",rating:4.3,reviews:120},
{slug:"ao-tee-den-short",name:"Áo Tee Đen Short",cat:["nam","nu"],price:189000,img:"assets/products/guno-tee-black-short.jpg",colors:["#2d3436","#f5f0e8"],sizes:["S","M","L","XL"],desc:"Áo tee đen basic.",rating:4.3,reviews:115},
{slug:"sun-jacket-beige",name:"Áo Chống Nắng Beige",cat:["phu-kien","nu"],price:349000,img:"assets/products/guno-sun-jacket-beige.jpg",colors:["#f5f0e8","#2c3e50"],sizes:["S","M","L","XL"],desc:"Áo khoác chống nắng UPF50+.",badge:"Hot",rating:4.9,reviews:204},
{slug:"sun-jacket-navy",name:"Áo Chống Nắng Navy",cat:["phu-kien","nam"],price:349000,img:"assets/products/guno-sun-jacket-navy.jpg",colors:["#2c3e50","#f5f0e8"],sizes:["M","L","XL","2XL"],desc:"Áo khoác chống nắng UPF50+.",rating:4.8,reviews:178},
{slug:"active-navy-short",name:"Quần Short Navy Active",cat:["the-thao","nam","sale"],price:179000,oldPrice:229000,img:"assets/products/guno-active-navy-short.jpg",colors:["#2c3e50","#2d3436"],sizes:["S","M","L","XL"],desc:"Quần short thể thao navy.",discount:20,rating:4.4,reviews:65},
{slug:"active-red-short",name:"Quần Short Đỏ Active",cat:["the-thao","sale"],price:169000,oldPrice:229000,img:"assets/products/guno-active-red-short.jpg",colors:["#d63031","#2d3436"],sizes:["S","M","L","XL"],desc:"Quần short thể thao đỏ.",discount:25,rating:4.3,reviews:42}
];
const CATEGORIES={nam:{title:"Thời trang Nam",banner:"assets/banners/banner-men.png"},nu:{title:"Thời trang Nữ",banner:"assets/banners/banner-women.png"},"the-thao":{title:"Đồ Thể Thao",banner:"assets/banners/banner-sport.png"},"phu-kien":{title:"Phụ Kiện",banner:"assets/banners/banner-accessories.png"},sale:{title:"SALE - Ưu đãi đến 50%",banner:"assets/banners/banner-sale.png"},new:{title:"Hàng Mới Về"}};
